### ISSUE TITLE
Webserver for Update Esp32 Firmware

### ISSUE THREAD

**Issue by pcbntt** [kubilaykerti/ESP32_02_Ethernet_And_WiFi_WebServer#1]
Hello my friend!
This example is what I was looking for a long time. The server over wifi and ethernet on ESP32. I have a need in one of my projects for a view page to read data and update the esp32 firmware. Do you have any examples contemplating these two functions?

**Comment by kubilaykerti** [comment]
Hello my friend.
If you examine the [aWOT ](https://github.com/kubilaykerti/ESP32_02_Ethernet_And_WiFi_WebServer/tree/main/lib/aWOT/examples/OTAUpdate)library I use in the project, it will solve your needs. I also use it in my products. I do system settings and system updates via webserver both over ethernet and wifi.
